
package ua.nure.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import ua.nure.entity.Airplane;
import ua.nure.entity.Ticket;

import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 *
 */
@WebService(name = "AirplaneService", targetNamespace = "http://nure.ua/service")
@XmlSeeAlso({
    ua.nure.entity.ObjectFactory.class,
    ua.nure.service.ObjectFactory.class
})
public interface AirplaneService {


    /**
     *
     * @param airplane
     * @return
     *     returns int
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://nure.ua/entity")
    @RequestWrapper(localName = "addAirplane", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.AddAirplane")
    @ResponseWrapper(localName = "addAirplaneResponse", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.AddAirplaneResponse")
    @Action(input = "http://nure.ua/service/AirplaneService/addAirplaneRequest", output = "http://nure.ua/service/AirplaneService/addAirplaneResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://nure.ua/service/AirplaneService/addAirplane/Fault/DAOException")
    })
    public int addAirplane(
        @WebParam(name = "Airplane", targetNamespace = "http://nure.ua/entity")
        Airplane airplane)
        throws DAOException_Exception
    ;

    /**
     *
     * @return
     *     returns java.util.List<ua.nure.entity.Airplane>
     */
    @WebMethod
    @WebResult(name = "listAirplanes", targetNamespace = "http://nure.ua/entity")
    @RequestWrapper(localName = "listAirplanes", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.ListAirplanes")
    @ResponseWrapper(localName = "listAirplanesResponse", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.ListAirplanesResponse")
    @Action(input = "http://nure.ua/service/AirplaneService/listAirplanesRequest", output = "http://nure.ua/service/AirplaneService/listAirplanesResponse")
    public List<Airplane> listAirplanes();

    /**
     *
     * @param ticket
     * @param airplaneId
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addTicket", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.AddTicket")
    @ResponseWrapper(localName = "addTicketResponse", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.AddTicketResponse")
    @Action(input = "http://nure.ua/service/AirplaneService/addTicketRequest", output = "http://nure.ua/service/AirplaneService/addTicketResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://nure.ua/service/AirplaneService/addTicket/Fault/DAOException")
    })
    public void addTicket(
        @WebParam(name = "airplaneId", targetNamespace = "")
        int airplaneId,
        @WebParam(name = "Ticket", targetNamespace = "http://nure.ua/entity")
        Ticket ticket)
        throws DAOException_Exception
    ;

    /**
     *
     * @param ticketNumber
     * @return
     *     returns ua.nure.entity.Ticket
     */
    @WebMethod
    @WebResult(name = "Ticket", targetNamespace = "http://nure.ua/entity")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.GetTicketResponse")
    @Action(input = "http://nure.ua/service/AirplaneService/getTicketRequest", output = "http://nure.ua/service/AirplaneService/getTicketResponse")
    public Ticket getTicket(
        @WebParam(name = "ticketNumber", targetNamespace = "")
        String ticketNumber);

    /**
     *
     * @param airplaneId
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeAirplane", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.RemoveAirplane")
    @ResponseWrapper(localName = "removeAirplaneResponse", targetNamespace = "http://nure.ua/service", className = "ua.nure.service.RemoveAirplaneResponse")
    @Action(input = "http://nure.ua/service/AirplaneService/removeAirplaneRequest", output = "http://nure.ua/service/AirplaneService/removeAirplaneResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://nure.ua/service/AirplaneService/removeAirplane/Fault/DAOException")
    })
    public void removeAirplane(
        @WebParam(name = "airplaneId", targetNamespace = "")
        int airplaneId)
        throws DAOException_Exception
    ;

}
