//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.06 at 01:32:15 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://nure.ua/entity", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.nure.entity;
